pipeline {
  agent {
    kubernetes {
      yaml """
        apiVersion: v1
        kind: Pod
        spec:
         containers:
         - name: gradle
          image: gradle
          command:
          - sleep
          args:
          - 99d
          volumeMounts:
          - name: shared-storage
           mountPath: /mnt    
         restartPolicy: Never
         volumes:
         - name: shared-storage
          persistentVolumeClaim:
           claimName: jenkins-pv-claim
         - name: kaniko-secret
          secret:
            secretName: dockercred
            items:
            - key: .dockerconfigjson
             path: config.json
      """
    }
  }
  stages {
    stage('Build a gradle project') {
      steps {
        git 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
        container('gradle') {
          sh '''
          cd Chapter08/sample1
          sed -i 's/minimum = 0.2/minimum = 0.1/' build.gradle
          sed -i '/checkstyle {/,/}/d' build.gradle 
          sed -i '/checkstyle/d' build.gradle 
          cat build.gradle
          chmod +x gradlew
          ./gradlew build
          echo "mv ./build/libs/calculator-0.0.1-SNAPSHOT.jar /mnt"
          '''
        }
      }
    }
    stage('TBD') {
      steps {
      }
    }
  }
}
