pipeline {
  agent {
    kubernetes {
      containerTemplate {
        name 'gradle'
        image 'gradle'
        command 'sleep'
        args '30d'
      }
    }
  }
  stages {
    stage('Build a gradle project but not really') {
      steps {
        git 'https://github.com/juggergnat/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
        container('gradle') {
          sh '''
          cd Chapter08/sample1
          sed -i 's/minimum = 0.2/minimum = 0.1/' build.gradle
          sed -i '/checkstyle {/,/}/d' build.gradle 
          sed -i '/checkstyle/d' build.gradle 
          cat build.gradle
          chmod +x gradlew
          echo "./gradlew build"
          echo "mv ./build/libs/calculator-0.0.1-SNAPSHOT.jar /mnt"
          '''
        }
      }
    }
    stage('Required stage 1: Test the staging environment in my local kubernetes cluster.') {
      steps {
        sh '''
          echo "./gradlew smokeTest -Dcalculator.url=http://calculator-service.staging.svc.cluster.local:8080"
        '''
      }
    }
    stage('Required stage 2: Start the calculator and hazelcast in GKE.') {
      steps {
        sh '''
          echo "From the Labbbby lab lab:"
          echo "To start using the GKE cluster, you must switch your context:"
          echo "  # kubectl config use-context [cluster]"
          echo "Okay, but what now?"
        '''
      }
    }
  }
  post {
    always {
      echo 'FUN FACT: The always conditional in post always runs first before other conditionals.'
      echo 'Immona do my garbage collection here.'
    }
    success  { echo 'End: success!'  }
    failure  { echo 'End: failure!'  }
    unstable { echo 'End: unstable!' }
    changed  { echo 'End: changed!'  }
  }
}
