apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: MYAPP
    release: MYREL
  name: example-rule-mongodb-conn
spec:
  groups:
  - name: example-rule-mongodb-conn
    rules:
    - alert: example-alert-mongodb-conn
      annotations:
        description: MYDES
        summary: MYSUM
      expr: MYRULE
      for: 2m
      labels:
        severity: MYSEV

