pipeline {
  agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
        name 'gradle'
        image 'gradle'
        command 'sleep'
        args '30d'
      }
      yaml """
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: gradle
            image: gradle
            command:
            - sleep
            args:
            - 99d
            volumeMounts:
            - name: shared-storage
              mountPath: /mnt
          - name: kaniko
            image: gcr.io/kaniko-project/executor:debug
            command:
            - sleep
            args:
            - 9999999
            volumeMounts:
            - name: shared-storage
              mountPath: /mnt
            - name: kaniko-secret
              mountPath: /kaniko/.docker
            restartPolicy: Never
            volumes:
            - name: shared-storage
              persistentVolumeClaim:
                claimName: jenkins-pv-claim
            - name: kaniko-secret
              secret:
                secretName: dockercred
                items:
                - key: .dockerconfigjson
                  path: config.json
      """
    }
  }
  
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/juggergnat/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }
    // From assignment: The CodeCoverage test should only run on the main branch.
    stage('Run pipeline against a gradle project - test MAIN - Code coverage') {
      when { branch 'main' }
      steps {
        echo 'Code coverage test on main branch.'
        sh """
          cd Chapter08/sample1;
          ./gradlew jacocoTestReport
          ./gradlew jacocoTestCoverageVerification
        """
      }
    }
    // From assignment: All other tests should run in the feature and playground branches.
    stage('Run pipeline against a gradle project - test OTHER - Code check') {
      when {
        anyOf {
          branch 'feature'
          branch 'playground'
        }
      }
      steps {
        echo 'Unit test and static code analysis on non-main branch.'
        sh """
          cd Chapter08/sample1; 
          ./gradlew test
          ./gradlew checkstyleMain
        """
      }
    }
  }

  post {
    always   {
      script {
        echo "Post always script: " + env.BRANCH_NAME
        if ( env.BRANCH_NAME == 'main' ) {
          // Code coverage test report.
          // publishHTML (target: [
          //   reportDir: 'Chapter08/sample1/build/reports/tests/test',
          //   reportFiles: 'index.html',
          //   reportName: "JaCoCo CC Report"
          // ])
        }
        if (env.BRANCH_NAME == 'feature' || env.BRANCH_NAME == 'playground') {
          // Unit test and static code analysis test report.
          // publishHTML (target: [
          //   reportDir: 'Chapter08/sample1/build/reports/checkstyle',
          //   reportFiles: 'main.html',
          //   reportName: "JaCoCo Checkstyle"
          // ])
        }
      }
      echo 'End: pipeline completed, yo!'
    }
    success  {
      script {
        echo "Post success script: " + env.BRANCH_NAME
        // Container should only create on success (main, feature branch, not playground).
        if ( env.BRANCH_NAME == 'main' ) {
          // repository/calculator:1.0
        }
        if ( env.BRANCH_NAME == 'feature' ) {
          // repository/calculator-feature:0.1
        }
      }
      echo 'End: tests pass!'
    }
    failure  { echo 'End: tests fail!' }
    unstable { echo 'End: run is unstable!' }
    changed  { echo 'End: pipeline run changed!' }
  }
}
