pipeline {
  agent {
    kubernetes {
      // Define the pod template with container template
      containerTemplate {
        name 'gradle'
        image 'gradle'
        command 'sleep'
        args '30d'
      }
    }
  }
  
  stages {
    stage('Checkout code and prepare environment') {
      steps {
        git url: 'https://github.com/juggergnat/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git', branch: 'w7'
        sh """
          cd Chapter08/sample1
          chmod +x gradlew
        """
      }
    }

    // From assignment: All other tests should run in the feature and playground branches.
    stage('Run pipeline against a gradle project - test OTHER - Code check') {
      when {
        anyOf {
          branch 'feature'
          branch 'playground'
        }
      }
      steps {
        echo 'Static code analysis on non-main branch.'
        sh """
          cd Chapter08/sample1; 
          ./gradlew test
          ./gradlew jacocoTestReport
          ./gradlew checkstyleMain
        """
        //post {
        //  always {
        //    echo 'Generating JaCoCo Checkstyle.'
        //    publishHTML (target: [
        //      reportDir: 'Chapter08/sample1/build/reports/checkstyle',
        //      reportFiles: 'main.html',
        //      reportName: "JaCoCo Checkstyle"
        //    ])
        //  }
        //  success { echo 'Checkstyle tests pass!' }
        //  failure { echo 'Checkstyle tests fail!' }
        //}
      }
    }

    // From assignment: The CodeCoverage test should only run on the main branch.
    stage('Run pipeline against a gradle project - test MAIN - Code coverage') {
      when { branch 'main' }
      steps {
        echo 'Code coverage test on main branch. Build 9.'
        sh """
          cd Chapter08/sample1;
          ./gradlew test
          ./gradlew jacocoTestReport
          ./gradlew checkstyleMain
          ./gradlew jacocoTestCoverageVerification
        """
        //post {
        //  always {
        //    echo 'Generating JaCoCo Report'
        //    publishHTML (target: [
        //      reportDir: 'Chapter08/sample1/build/reports/tests/test',
        //      reportFiles: 'index.html',
        //      reportName: "JaCoCo Report"
        //    ])
        //  }
        //  success { echo 'All other tests pass!' }
        //  failure { echo 'All other tests fail!' }
        //}
      }
    }
  }

  post {
    always   {
      script {
        if ( env.BRANCH_NAME == 'main' ) {
          publishHTML (target: [
            reportDir: 'Chapter08/sample1/build/reports/tests/test',
            reportFiles: 'index.html',
            reportName: "JaCoCo Report"
          ])
          publishHTML (target: [
            reportDir: 'Chapter08/sample1/build/reports/checkstyle',
            reportFiles: 'main.html',
            reportName: "JaCoCo Checkstyle"
          ])
        }
      }
      echo 'End: pipeline completed, yo!'
    }
    success  { echo 'End: tests pass!' }
    failure  { echo 'End: tests fail!' }
    unstable { echo 'End: run is unstable!' }
    changed  { echo 'End: pipeline run changed!' }
  }
}
