pipeline {
  agent {
    kubernetes {
      yaml """
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: centos
            image: centos
            command:
            - sleep
            args:
            - 99d
          - name: gradle
            image: gradle:jdk8
            command:
            - sleep
            args:
            - 99d
          restartPolicy: Never
      """
    }
  }
  stages {
    stage('Stage 1: Start a calculator with Chapter08/sample1 code.') {
      steps {
        git 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
        container('centos') {
          sh '''
            cd Chapter08/sample1
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            ./kubectl apply -f calculator.yaml
            ./kubectl apply -f hazelcast.yaml
            sleep 15
          '''
        }
      }
    }
    stage('Stage 2: Test calculator per assignment requirements.') {
      steps {
        git 'https://github.com/dlambrig/Continuous-Delivery-with-Docker-and-Jenkins-Second-Edition.git'
        container('gradle') {
          sh '''
            cd Chapter09/sample3
            # Skip acceptance tests for now.
            # chmod +x gradlew
            # ./gradlew acceptanceTest -Dcalculator.url=http://calculator-service:8080
            test $(curl calculator-service:8080/sum?a=6\\&b=2) -eq 8 \
              && echo 'Test 1: Pass. Addition. 6 + 2 = 8.' \
              || echo 'Test 1: Fail. Addition. 6 + 2 ≠ 8.'
            test $(curl calculator-service:8080/div?a=6\\&b=2) -eq 3 \
              && echo 'Test 2: Pass. Division. 6 / 2 = 3.' \
              || echo 'Test 2: Fail. Division. 6 / 2 ≠ 3.'
            test $(curl calculator-service:8080/div?a=0\\&b=2) -eq 0 \
              && echo 'Test 3: Pass. Division. 0 / 2 = 0.' \
              || echo 'Test 3: Fail. Division. 0 / 2 ≠ 0.'
            test $(curl calculator-service:8080/div?a=2\\&b=0) -eq 0 \
              && echo 'Test 4: Fail. Division by 0 captured and prevented (unexpected behaviour).' \
              || echo 'Test 4: Pass. Division by 0 not handled and generated an error (expected behavior).'
          '''
        }
      }
    }
  }
  post {
    always {
      // Author note: Previous changes to named containers persist. Neat.
      // Author note: Environment variables in named containers do not persist. That's fine.
      container('centos') {
        sh '''
          echo 'From assignment: Delete the deployments on completion, outcome regardless.'
          echo 'Author note: Services AND Deployments should be deleted. Namespace context: devops-tools.'
          cd Chapter08/sample1
          ./kubectl delete service calculator-service
          ./kubectl delete service hazelcast
          DEP_1=`./kubectl get deployment -o custom-columns=":metadata.name" --no-headers=true -l app=calculator`
          DEP_2=`./kubectl get deployment -o custom-columns=":metadata.name" --no-headers=true -l app=hazelcast`
          [[ ! -z "$DEP_1" ]] && ./kubectl delete deployment $DEP_1 || echo "Cannot delete calculator deployment."
          [[ ! -z "$DEP_2" ]] && ./kubectl delete deployment $DEP_2 || echo "Cannot delete hazelcast deployment."
          ./kubectl get pod -n devops-tools
          ./kubectl get services -n devops-tools
          ./kubectl get deployments -n devops-tools
        '''
      }
    }
  }
}
