podTemplate(yaml: '''
    apiVersion: v1
    kind: Pod
    spec:
      containers:
      - name: cloud-sdk
        image: google/cloud-sdk:latest
        command:
        - sleep
        args:
        - 9999999
        volumeMounts:
        - name: shared-storage
          mountPath: /mnt
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: [[[`cat ~/Files/devops/.sdkkey`]]]
        - name: GOOGLE_PROJECT
          value: [[[`cat ~/Files/devops/.sdkproj`]]]
      restartPolicy: Never
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: jenkins-pv-claim
      - name: google-cloud-key
        secret:
          secretName: sdk-key          
''') {
  node(POD_LABEL) {
    stage('Deploying to prod') {
      container('cloud-sdk') {
        stage('Build a gradle project') {
          sh '''
          echo 'namespaces in the staging environment'
          kubectl get ns
          echo $GOOGLE_APPLICATION_CREDENTIALS
          echo $GOOGLE_PROJECT
          gcloud auth login --cred-file=$GOOGLE_APPLICATION_CREDENTIALS --no-launch-browser
          gcloud container clusters get-credentials hello-cluster --region us-central1 --project $GOOGLE_PROJECT
          echo 'namespaces in the prod environment'
          kubectl get ns
          '''
        }
      }
    }
  }
}
